### ISSUE TITLE
How to update fast-geoip database? Is there some scripts or cli？

### ISSUE THREAD

**Issue by Steve2050** [onramper/fast-geoip#2]

**Comment by corollari** [comment]
You can update the database with the following commands:
```
export MAXMIND_LICENSE_KEY=XXXX
python downloadDatabases.py
python processGeoIpCsv.py
```

The CI also runs this periodically and uploads new versions of the package to npm that have an updated database.

**Comment by corollari** [comment]
@Steve2050 Did I answer your question?

**Comment by Steve2050** [comment]
> You can update the database with the following commands:
> 
> ```
> export MAXMIND_LICENSE_KEY=XXXX
> python downloadDatabases.py
> python processGeoIpCsv.py
> ```
> 
> The CI also runs this periodically and uploads new versions of the package to npm that have an updated database.

Excellent work and it’s done，now i'm using it on serverless.

**Comment by corollari** [comment]
Great, let me know if you'd like me to change something :smile:
