### ISSUE TITLE
Lookups not working correctly

### ISSUE THREAD

**Issue by chiqomar** [onramper/fast-geoip#7]
We were looking at replacing our version of `geoip-lite` with this library, but realized that the results returned from this library are incorrect; using the example IP (`207.97.227.239`) in the Readme results in the following:
```json
{
  range: [ 3479289856, 3479306240 ],
  country: 'US',
  region: '',
  eu: '0',
  timezone: 'America/Chicago',
  city: '',
  ll: [ 37.751, -97.822 ],
  metro: 0,
  area: 1000
}
```

Tried this locally, as well as in the RunKit instance with the same result.

**Comment by gugu** [comment]
I don't think it is a bug - geoip-lite updates database and IP address can change location over time

**Comment by chiqomar** [comment]
Right, but, you should probably update your readme to match, or use another IP, otherwise trying the example doesn't work. In any case, no one's active on this anyway. Gonna close the issue.
